### ISSUE TITLE
No data for File Size metric

### ISSUE THREAD

**Issue by kalkrishnan** [SonarSource/sonar-custom-plugin-example#5]
I am trying to understand how to implement metrics and installed this plugin but it keeps saying no data found, even when I changed the files to:
 Iterable<InputFile> files = fs.inputFiles(fs.predicates().all());

Not sure how I can get this to generate data.

**Comment by kalkrishnan** [comment]
Even hardcoded the value:

    context.<Integer>newMeasure()
    .forMetric(FILENAME_SIZE)
    .withValue(20)
    .save();

Still says no data

**Comment by dbmeneses** [comment]
@kalkrishnan please open a topic in the sonarqube google group. It would also be useful to have more information about what you are analyzing and the logs in debug.
