### ISSUE TITLE
Can you disable plugin from running under some condition?

### ISSUE THREAD

**Issue by nancy-gomez** [SonarSource/sonar-custom-plugin-example#8]
Hello, so I'm in the process of developing a plugin and I wanted to know if there is a way within the plugin code to skip running all together -- to not run under some condition? For example if the plugin can identify the branch is not main branch or that project is not an android / ios project. Is that possible?  

For example sonar-swift, I'm sure it doesn't run through every file to check if it is swift, how and when can you cancel execution of the plugin?

**Comment by wouter-admiraal-sonarsource** [comment]
Hi Nancy.

Terribly sorry for the late reply. We don't really track issues on this repo...

For support and help, please use our [community forum](https://community.sonarsource.com/).
